# -*- coding: utf-8 -*-
"""AgriTrustNet++_End_to_End_IEEE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YKONvbqmKUHaNvFxA4ICwpknofv0Jiz7
"""

# ============================================================
# Project : AgriTrustNet++
# Title   : AgriTrustNet++: A Reliability-Aware Multi-Branch
#           Deep Learning Framework with Cross-Attention
#           Feature Fusion for Explainable Rice Leaf Disease
#           Classification and Severity Assessment
#
# Author  : Harini
# Platform: Google Colab
# ============================================================

"""
Project Workflow

1. Dataset Collection
2. Data Cleaning
3. Dataset Visualization
4. Image Quality Assessment
5. Adaptive Image Enhancement
6. Data Augmentation
7. Train / Validation / Test Split
8. Multi-Branch Deep Learning Model
9. Cross-Attention Feature Fusion
10. Disease Classification
11. Severity Prediction
12. Confidence Prediction
13. Monte Carlo Dropout
14. Reliability Fusion Module
15. Explainable AI (Grad-CAM++)
16. Treatment Recommendation
17. PDF Report Generation
18. Streamlit Deployment

"""

# ============================================================
# Install Required Libraries
# ============================================================

!pip install -q timm
!pip install -q grad-cam
!pip install -q albumentations
!pip install -q opencv-python
!pip install -q kaggle
!pip install -q reportlab
!pip install -q torchmetrics
!pip install -q scikit-learn
!pip install -q matplotlib
!pip install -q seaborn
!pip install -q pandas
!pip install -q pillow
!pip install -q tqdm
!pip install -q faiss-cpu

# ============================================================
# Import Libraries
# ============================================================

import os
import cv2
import math
import time
import random
import shutil
import warnings
import zipfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.optim as optim

from torch.utils.data import DataLoader
from torch.utils.data import random_split

from torchvision import transforms
from torchvision.datasets import ImageFolder

import timm

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

warnings.filterwarnings("ignore")

print("Libraries Imported Successfully")

# ============================================================
# GPU Check
# ============================================================

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("="*40)
print("Device :", device)

if torch.cuda.is_available():
    print("GPU :", torch.cuda.get_device_name(0))
    print("CUDA Version :", torch.version.cuda)

print("="*40)

# ============================================================
# Mount Google Drive
# ============================================================

from google.colab import drive

drive.mount('/content/drive')

# ============================================================
# Create Project Directory
# ============================================================

PROJECT_DIR = "/content/AgriTrustNet++"

folders = [

    "Dataset",
    "Models",
    "Reports",
    "Results",
    "Heatmaps",
    "Checkpoints"

]

for folder in folders:
    os.makedirs(os.path.join(PROJECT_DIR, folder), exist_ok=True)

print("Project folders created successfully.")

from google.colab import files

print("Upload your kaggle.json file")

files.upload()

import os
import shutil

# Create Kaggle directory
os.makedirs("/root/.kaggle", exist_ok=True)

# Copy kaggle.json
shutil.copy("kaggle.json", "/root/.kaggle/kaggle.json")

# Set permission
os.chmod("/root/.kaggle/kaggle.json", 600)

print("Kaggle API Configured Successfully")

# Rice Disease Dataset

!kaggle datasets download -d nirmalsankalana/rice-leaf-disease-image

# Healthy Rice Leaf Dataset

!kaggle datasets download -d rajkumar898/rice-plant-dataset

import os

DATASET_DIR = "/content/AgriTrustNet++/Dataset"

os.makedirs(DATASET_DIR, exist_ok=True)

print(DATASET_DIR)

import zipfile

with zipfile.ZipFile("rice-leaf-disease-image.zip", 'r') as zip_ref:
    zip_ref.extractall(DATASET_DIR)

print("Disease Dataset Extracted")

with zipfile.ZipFile("rice-plant-dataset.zip", 'r') as zip_ref:
    zip_ref.extractall(DATASET_DIR)

print("Healthy Dataset Extracted")

import os

for root, dirs, files in os.walk(DATASET_DIR):
    print(root)

import os

print(os.path.exists("/content/AgriTrustNet++/Dataset_Final"))

import os

FINAL_DATASET = "/content/AgriTrustNet++/Dataset_Final"

classes = [
    "Healthy",
    "Brown_Spot",
    "Leaf_Blast",
    "Bacterial_Blight",
    "Tungro"
]

os.makedirs(FINAL_DATASET, exist_ok=True)

for cls in classes:
    os.makedirs(os.path.join(FINAL_DATASET, cls), exist_ok=True)

print("Folders Created Successfully!")

import os

for root, dirs, files in os.walk(FINAL_DATASET):
    print(root)

import os
import shutil
from tqdm import tqdm

healthy_source = "/content/AgriTrustNet++/Dataset/Rice Seed Dataset/Healthy_Images"
healthy_dest = "/content/AgriTrustNet++/Dataset_Final/Healthy"

count = 0

for img in tqdm(os.listdir(healthy_source)):
    src = os.path.join(healthy_source, img)

    if os.path.isfile(src):
        shutil.copy2(src, healthy_dest)
        count += 1

print(f"✅ Healthy Images Copied : {count}")

brown_source = "/content/AgriTrustNet++/Dataset/Brownspot"
brown_dest = "/content/AgriTrustNet++/Dataset_Final/Brown_Spot"

count = 0

for img in tqdm(os.listdir(brown_source)):
    src = os.path.join(brown_source, img)

    if os.path.isfile(src):
        shutil.copy2(src, brown_dest)
        count += 1

print(f"✅ Brown Spot Images Copied : {count}")

blast_source = "/content/AgriTrustNet++/Dataset/Blast"
blast_dest = "/content/AgriTrustNet++/Dataset_Final/Leaf_Blast"

count = 0

for img in tqdm(os.listdir(blast_source)):
    src = os.path.join(blast_source, img)

    if os.path.isfile(src):
        shutil.copy2(src, blast_dest)
        count += 1

print(f"✅ Blast Images Copied : {count}")

bacterial_source = "/content/AgriTrustNet++/Dataset/Bacterialblight"
bacterial_dest = "/content/AgriTrustNet++/Dataset_Final/Bacterial_Blight"

count = 0

for img in tqdm(os.listdir(bacterial_source)):
    src = os.path.join(bacterial_source, img)

    if os.path.isfile(src):
        shutil.copy2(src, bacterial_dest)
        count += 1

print(f"✅ Bacterial Blight Images Copied : {count}")

tungro_source = "/content/AgriTrustNet++/Dataset/Tungro"
tungro_dest = "/content/AgriTrustNet++/Dataset_Final/Tungro"

count = 0

for img in tqdm(os.listdir(tungro_source)):
    src = os.path.join(tungro_source, img)

    if os.path.isfile(src):
        shutil.copy2(src, tungro_dest)
        count += 1

print(f"✅ Tungro Images Copied : {count}")

import os

print("=" * 60)
print("FINAL DATASET SUMMARY")
print("=" * 60)

total = 0

for cls in sorted(os.listdir(FINAL_DATASET)):
    path = os.path.join(FINAL_DATASET, cls)

    if os.path.isdir(path):
        n = len(os.listdir(path))
        total += n
        print(f"{cls:<20} : {n}")

print("=" * 60)
print(f"Total Images : {total}")
print("=" * 60)

from PIL import Image
import os

corrupted = []

for cls in os.listdir(FINAL_DATASET):

    class_path = os.path.join(FINAL_DATASET, cls)

    if not os.path.isdir(class_path):
        continue

    for img in os.listdir(class_path):

        img_path = os.path.join(class_path, img)

        try:
            Image.open(img_path).verify()

        except Exception:
            corrupted.append(img_path)

print("="*60)
print("Corrupted Images :", len(corrupted))
print("="*60)

for img in corrupted[:10]:
    print(img)

for img in corrupted:
    os.remove(img)

print("Removed", len(corrupted), "corrupted images")

from collections import Counter

extensions = Counter()

for cls in os.listdir(FINAL_DATASET):

    path = os.path.join(FINAL_DATASET, cls)

    if not os.path.isdir(path):
        continue

    for img in os.listdir(path):

        ext = os.path.splitext(img)[1].lower()

        extensions[ext] += 1

print("="*50)

for ext, count in extensions.items():
    print(ext, ":", count)

print("="*50)

from PIL import Image
import numpy as np

widths = []
heights = []

for cls in os.listdir(FINAL_DATASET):

    folder = os.path.join(FINAL_DATASET, cls)

    if not os.path.isdir(folder):
        continue

    for img in os.listdir(folder):

        path = os.path.join(folder, img)

        try:

            image = Image.open(path)

            w, h = image.size

            widths.append(w)
            heights.append(h)

        except:
            pass

print("="*50)
print("Minimum Width :", min(widths))
print("Maximum Width :", max(widths))
print("Average Width :", np.mean(widths))

print()

print("Minimum Height :", min(heights))
print("Maximum Height :", max(heights))
print("Average Height :", np.mean(heights))
print("="*50)

import pandas as pd

stats = []

for cls in sorted(os.listdir(FINAL_DATASET)):

    folder = os.path.join(FINAL_DATASET, cls)

    if not os.path.isdir(folder):
        continue

    stats.append([cls, len(os.listdir(folder))])

df = pd.DataFrame(stats, columns=["Class", "Images"])

display(df)

print()

print("Total Images :", df["Images"].sum())

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.bar(df["Class"], df["Images"])

plt.title("Rice Leaf Disease Dataset Distribution")

plt.xlabel("Class")

plt.ylabel("Number of Images")

plt.xticks(rotation=20)

plt.show()

import cv2
import numpy as np
import pandas as pd
import os
from PIL import Image

def blur_score(image):

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    return cv2.Laplacian(gray, cv2.CV_64F).var()

def brightness_score(image):

    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

    return np.mean(hsv[:,:,2])

def contrast_score(image):

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    return gray.std()

def sharpness_score(image):

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    gx = cv2.Sobel(gray, cv2.CV_64F,1,0)

    gy = cv2.Sobel(gray, cv2.CV_64F,0,1)

    magnitude = np.sqrt(gx**2 + gy**2)

    return magnitude.mean()

def image_quality_analysis(image_path):

    image = cv2.imread(image_path)

    blur = blur_score(image)

    brightness = brightness_score(image)

    contrast = contrast_score(image)

    sharpness = sharpness_score(image)

    return {

        "Blur": blur,

        "Brightness": brightness,

        "Contrast": contrast,

        "Sharpness": sharpness

    }

healthy_folder = os.path.join(FINAL_DATASET, "Healthy")

sample = os.listdir(healthy_folder)[0]

sample_path = os.path.join(healthy_folder, sample)

scores = image_quality_analysis(sample_path)

scores

import matplotlib.pyplot as plt

img = Image.open(sample_path)

plt.figure(figsize=(5,5))

plt.imshow(img)

plt.axis("off")

plt.title("Sample Image")

plt.show()

for k,v in scores.items():

    print(f"{k:<15}: {round(v,2)}")

import random

records = []

for cls in sorted(os.listdir(FINAL_DATASET)):

    folder = os.path.join(FINAL_DATASET, cls)

    images = random.sample(
        os.listdir(folder),
        min(50, len(os.listdir(folder)))
    )

    for img in images:

        path = os.path.join(folder,img)

        s = image_quality_analysis(path)

        s["Class"] = cls

        records.append(s)

quality_df = pd.DataFrame(records)

quality_df.head()

quality_df.groupby("Class").mean().round(2)

import matplotlib.pyplot as plt

metrics = ["Blur","Brightness","Contrast","Sharpness"]

for metric in metrics:

    plt.figure(figsize=(8,4))

    quality_df.boxplot(column=metric, by="Class")

    plt.title(metric)

    plt.suptitle("")

    plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

def single_scale_retinex(image, sigma=30):

    image = image.astype(np.float32) + 1.0

    blur = cv2.GaussianBlur(image, (0, 0), sigma)

    retinex = np.log(image) - np.log(blur)

    return retinex

def multi_scale_retinex(image):

    sigmas = [15, 80, 250]

    retinex = np.zeros_like(image, dtype=np.float32)

    for sigma in sigmas:
        retinex += single_scale_retinex(image, sigma)

    retinex /= len(sigmas)

    return retinex

def color_restoration(image):

    image = image.astype(np.float32) + 1

    intensity = np.sum(image, axis=2, keepdims=True)

    restoration = np.log(125 * image) - np.log(intensity)

    return restoration

def enhance_image(image):

    image = image.astype(np.float32)

    retinex = multi_scale_retinex(image)

    restore = color_restoration(image)

    result = retinex * restore

    for i in range(3):

        channel = result[:, :, i]

        channel = cv2.normalize(
            channel,
            None,
            0,
            255,
            cv2.NORM_MINMAX
        )

        result[:, :, i] = channel

    return result.astype(np.uint8)

sample_path = os.path.join(
    FINAL_DATASET,
    "Healthy",
    os.listdir(os.path.join(FINAL_DATASET, "Healthy"))[0]
)

image = cv2.imread(sample_path)

image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

enhanced = enhance_image(image)

plt.figure(figsize=(12,6))

plt.subplot(1,2,1)

plt.imshow(image)

plt.title("Original")

plt.axis("off")

plt.subplot(1,2,2)

plt.imshow(enhanced)

plt.title("Enhanced")

plt.axis("off")

plt.show()

ENHANCED_DATASET = "/content/AgriTrustNet++/Enhanced_Dataset"

os.makedirs(ENHANCED_DATASET, exist_ok=True)

for cls in sorted(os.listdir(FINAL_DATASET)):

    src_folder = os.path.join(FINAL_DATASET, cls)

    dst_folder = os.path.join(ENHANCED_DATASET, cls)

    os.makedirs(dst_folder, exist_ok=True)

    print(f"Processing {cls}...")

    for img_name in os.listdir(src_folder):

        src = os.path.join(src_folder, img_name)

        image = cv2.imread(src)

        if image is None:
            continue

        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        enhanced = enhance_image(image)

        enhanced = cv2.cvtColor(enhanced, cv2.COLOR_RGB2BGR)

        cv2.imwrite(os.path.join(dst_folder, img_name), enhanced)

print("Dataset Enhancement Completed!")

import torch
from torchvision import transforms
from torch.utils.data import random_split
from torchvision.datasets import ImageFolder

IMG_SIZE = 224

train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.RandomRotation(20),
    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2,
        hue=0.1
    ),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

test_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

dataset = ImageFolder(
    root=FINAL_DATASET,
    transform=train_transform
)

print("Classes :", dataset.classes)
print("Total Images :", len(dataset))

train_size = int(0.70 * len(dataset))
val_size = int(0.15 * len(dataset))
test_size = len(dataset) - train_size - val_size

train_dataset, val_dataset, test_dataset = random_split(
    dataset,
    [train_size, val_size, test_size],
    generator=torch.Generator().manual_seed(42)
)

print("Train :", len(train_dataset))
print("Validation :", len(val_dataset))
print("Test :", len(test_dataset))

val_dataset.dataset.transform = test_transform
test_dataset.dataset.transform = test_transform

from torch.utils.data import DataLoader

BATCH_SIZE = 32

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

images, labels = next(iter(train_loader))

print("Image Batch Shape :", images.shape)
print("Label Batch Shape :", labels.shape)

import cv2
import numpy as np
import os
import pandas as pd
from tqdm import tqdm

def segment_leaf(image):

    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

    lower_green = np.array([20,20,20])
    upper_green = np.array([100,255,255])

    mask = cv2.inRange(
        hsv,
        lower_green,
        upper_green
    )

    return mask

def detect_disease_region(image):

    hsv = cv2.cvtColor(
        image,
        cv2.COLOR_BGR2HSV
    )


    lower_disease = np.array(
        [5,20,20]
    )

    upper_disease = np.array(
        [40,255,255]
    )


    disease_mask = cv2.inRange(
        hsv,
        lower_disease,
        upper_disease
    )


    return disease_mask

def calculate_severity(image):

    leaf_mask = segment_leaf(image)

    disease_mask = detect_disease_region(image)


    leaf_pixels = np.sum(leaf_mask > 0)

    disease_pixels = np.sum(disease_mask > 0)


    if leaf_pixels == 0:

        return 0, "Healthy"


    severity_percentage = (
        disease_pixels /
        leaf_pixels
    ) * 100



    if severity_percentage < 10:

        label = "Healthy"


    elif severity_percentage < 30:

        label = "Mild"


    elif severity_percentage < 60:

        label = "Moderate"


    else:

        label = "Severe"



    return severity_percentage, label

import os

for root, dirs, files in os.walk("/content"):
    if "Dataset_Final" in root or "AgriTrustNet" in root:
        print(root)

FINAL_DATASET = "/content/AgriTrustNet++/Dataset"

import os

print(os.listdir("/content"))

from google.colab import drive

drive.mount('/content/drive')

import os

PROJECT_PATH = "/content/drive/MyDrive/AgriTrustNet++"

os.makedirs(PROJECT_PATH, exist_ok=True)

print("Project folder created ✅")

!pip install kaggle

from google.colab import files

files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d rajkumar898/rice-plant-dataset

import zipfile

zip_path="/content/rice-plant-dataset.zip"

extract_path=PROJECT_PATH+"/Raw_Dataset"

with zipfile.ZipFile(zip_path,'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted ✅")

import os

for root,dirs,files in os.walk(extract_path):
    print(root)

import os

RAW_PATH = "/content/drive/MyDrive/AgriTrustNet++/Raw_Dataset"

for root, dirs, files in os.walk(RAW_PATH):
    print(root)

import os

FINAL_DATASET = "/content/drive/MyDrive/AgriTrustNet++/Dataset_Final"

classes = [
    "Healthy",
    "Brown_Spot",
    "Leaf_Blast",
    "Bacterial_Blight",
    "Tungro"
]


for cls in classes:
    os.makedirs(
        os.path.join(FINAL_DATASET, cls),
        exist_ok=True
    )

print("Dataset folders created ✅")

import shutil
from tqdm import tqdm

source = "/content/drive/MyDrive/AgriTrustNet++/Raw_Dataset/Rice Seed Dataset/Healthy_Images"

destination = os.path.join(
    FINAL_DATASET,
    "Healthy"
)


count=0

for img in tqdm(os.listdir(source)):

    src=os.path.join(source,img)

    if os.path.isfile(src):

        shutil.copy2(src,destination)
        count+=1


print("Healthy copied:",count)

import os

RAW_DISEASE_PATH="/content/drive/MyDrive/AgriTrustNet++/Raw_Dataset"

print(os.listdir(RAW_DISEASE_PATH))

mapping = {
    "Brownspot": "Brown_Spot",
    "Blast": "Leaf_Blast",
    "Bacterialblight": "Bacterial_Blight",
    "Tungro": "Tungro"
}

print("Mapping created ✅")

print(os.listdir(RAW_DISEASE_PATH))

RAW_DISEASE_PATH = "/content/drive/MyDrive/AgriTrustNet++/Raw_Dataset/Rice Seed Dataset"

print(os.listdir(RAW_DISEASE_PATH))

UNHEALTHY_PATH = "/content/drive/MyDrive/AgriTrustNet++/Raw_Dataset/Rice Seed Dataset/Unhealthy_Images"

print(os.listdir(UNHEALTHY_PATH))

RAW_DISEASE_PATH = "/content/drive/MyDrive/AgriTrustNet++/Raw_Dataset/Rice Seed Dataset/Unhealthy_Images"

import os

UNHEALTHY_PATH="/content/drive/MyDrive/AgriTrustNet++/Raw_Dataset/Rice Seed Dataset/Unhealthy_Images"

print(os.listdir(UNHEALTHY_PATH))

!kaggle datasets download -d vbookshelf/rice-leaf-diseases

import zipfile

zip_path="/content/rice-leaf-diseases.zip"

extract="/content/drive/MyDrive/AgriTrustNet++/Disease_Dataset"

with zipfile.ZipFile(zip_path,'r') as z:
    z.extractall(extract)

print("Disease dataset extracted ✅")

import os

for root,dirs,files in os.walk(extract):
    print(root)

import os

DISEASE_PATH="/content/drive/MyDrive/AgriTrustNet++/Disease_Dataset/rice_leaf_diseases"


for folder in os.listdir(DISEASE_PATH):

    path=os.path.join(DISEASE_PATH,folder)

    if os.path.isdir(path):

        print(folder,":",len(os.listdir(path)))

!kaggle datasets list -s "rice plant dataset"

!kaggle datasets download -d rajkumar898/rice-plant-dataset

import zipfile
import os

zip_path="/content/rice-plant-dataset.zip"

extract_path="/content/drive/MyDrive/AgriTrustNet++/Large_Dataset"


os.makedirs(extract_path,exist_ok=True)


with zipfile.ZipFile(zip_path,'r') as z:
    z.extractall(extract_path)


print("Large dataset extracted ✅")

for root,dirs,files in os.walk(extract_path):
    print(root)

import os

SEARCH_PATH="/content/drive/MyDrive/AgriTrustNet++/Large_Dataset"

for root,dirs,files in os.walk(SEARCH_PATH):
    if len(files)>0:
        print(root, " --> ", len(files))

!kaggle datasets list -s "rice leaf disease"

!kaggle datasets list -s "rice disease classification"

!kaggle datasets download -d nirmalsankalana/rice-leaf-disease-image

import zipfile

zip_path="/content/rice-leaf-disease-image.zip"

extract="/content/drive/MyDrive/AgriTrustNet++/Main_Dataset"

with zipfile.ZipFile(zip_path,'r') as z:
    z.extractall(extract)

print("Main dataset extracted ✅")

import os

for root,dirs,files in os.walk(extract):
    print(root)

import os

FINAL_DATASET="/content/drive/MyDrive/AgriTrustNet++/Dataset_Final"

classes=[
    "Healthy",
    "Bacterial_Blight",
    "Leaf_Blast",
    "Brown_Spot",
    "Tungro"
]


for cls in classes:
    os.makedirs(
        os.path.join(FINAL_DATASET,cls),
        exist_ok=True
    )

print("Final folders created ✅")

import os

FINAL_DATASET="/content/drive/MyDrive/AgriTrustNet++/Dataset_Final"

classes=[
    "Healthy",
    "Bacterial_Blight",
    "Leaf_Blast",
    "Brown_Spot",
    "Tungro"
]


for cls in classes:
    os.makedirs(
        os.path.join(FINAL_DATASET,cls),
        exist_ok=True
    )

print("Final folders created ✅")

import os

FINAL_DATASET="/content/drive/MyDrive/AgriTrustNet++/Dataset_Final"

classes=[
    "Healthy",
    "Bacterial_Blight",
    "Leaf_Blast",
    "Brown_Spot",
    "Tungro"
]


for cls in classes:
    os.makedirs(
        os.path.join(FINAL_DATASET,cls),
        exist_ok=True
    )

print("Final folders created ✅")

import shutil
from tqdm import tqdm
import os


SOURCE="/content/drive/MyDrive/AgriTrustNet++/Main_Dataset"


for old,new in mapping.items():

    src_folder=os.path.join(SOURCE,old)

    dst_folder=os.path.join(FINAL_DATASET,new)


    count=0

    for img in tqdm(os.listdir(src_folder)):

        src=os.path.join(src_folder,img)

        if os.path.isfile(src):

            shutil.copy2(src,dst_folder)
            count+=1


    print(new,":",count)

healthy_source="/content/drive/MyDrive/AgriTrustNet++/Large_Dataset/Rice Seed Dataset/Healthy_Images"

healthy_dest="/content/drive/MyDrive/AgriTrustNet++/Dataset_Final/Healthy"


count=0

for img in tqdm(os.listdir(healthy_source)):

    src=os.path.join(healthy_source,img)

    if os.path.isfile(src):

        shutil.copy2(src,healthy_dest)
        count+=1


print("Healthy :",count)

import os


print("="*50)
print("FINAL DATASET SUMMARY")
print("="*50)


total=0


for cls in sorted(os.listdir(FINAL_DATASET)):

    path=os.path.join(FINAL_DATASET,cls)

    if os.path.isdir(path):

        n=len(os.listdir(path))

        total+=n

        print(cls,":",n)


print("="*50)
print("TOTAL IMAGES :",total)
print("="*50)

import os
from PIL import Image

FINAL_DATASET="/content/drive/MyDrive/AgriTrustNet++/Dataset_Final"

corrupted=[]

for cls in os.listdir(FINAL_DATASET):

    folder=os.path.join(FINAL_DATASET,cls)

    for img in os.listdir(folder):

        path=os.path.join(folder,img)

        try:
            image=Image.open(path)
            image.verify()

        except:
            corrupted.append(path)


print("Corrupted images:",len(corrupted))

for x in corrupted[:10]:
    print(x)

!pip install imagehash

import os
import imagehash
from PIL import Image
from tqdm import tqdm


FINAL_DATASET="/content/drive/MyDrive/AgriTrustNet++/Dataset_Final"


hashes = {}
duplicates = []


for cls in os.listdir(FINAL_DATASET):

    folder = os.path.join(FINAL_DATASET, cls)

    print("Checking:", cls)

    for img in tqdm(os.listdir(folder)):

        path = os.path.join(folder, img)

        try:
            image = Image.open(path)

            img_hash = imagehash.phash(image)


            if img_hash in hashes:

                duplicates.append(
                    (path, hashes[img_hash])
                )

            else:
                hashes[img_hash] = path


        except:
            pass



print("==============================")
print("Duplicate images found:", len(duplicates))
print("==============================")

duplicate_percentage = (3005 / 6433) * 100

print("Duplicate percentage:", duplicate_percentage)

from collections import Counter

dup_classes=[]

for item in duplicates:

    img1=item[0]
    img2=item[1]

    c1=img1.split("/")[-2]
    c2=img2.split("/")[-2]

    dup_classes.append(
        (c1,c2)
    )


counter=Counter(dup_classes)


for k,v in counter.most_common(20):
    print(k,":",v)

import os
import shutil
import imagehash
from PIL import Image
from tqdm import tqdm


SOURCE="/content/drive/MyDrive/AgriTrustNet++/Dataset_Final"

CLEAN="/content/drive/MyDrive/AgriTrustNet++/Dataset_Clean"


os.makedirs(CLEAN,exist_ok=True)


for cls in os.listdir(SOURCE):

    src_folder=os.path.join(SOURCE,cls)

    dst_folder=os.path.join(CLEAN,cls)

    os.makedirs(dst_folder,exist_ok=True)


    hashes=set()

    count=0
    removed=0


    print("\nProcessing:",cls)


    for img in tqdm(os.listdir(src_folder)):

        src=os.path.join(src_folder,img)

        try:

            image=Image.open(src)

            h=imagehash.phash(image)


            if h not in hashes:

                hashes.add(h)

                shutil.copy2(
                    src,
                    dst_folder
                )

                count+=1


            else:

                removed+=1


        except:
            pass


    print("Kept:",count)
    print("Removed duplicates:",removed)

import os


total=0

for cls in sorted(os.listdir(CLEAN)):

    path=os.path.join(CLEAN,cls)

    n=len(os.listdir(path))

    total+=n

    print(cls,":",n)


print("TOTAL CLEAN IMAGES:",total)

import os
from sklearn.model_selection import train_test_split
import shutil
from tqdm import tqdm


SOURCE="/content/drive/MyDrive/AgriTrustNet++/Dataset_Clean"

DEST="/content/drive/MyDrive/AgriTrustNet++/Dataset_Split"


classes=os.listdir(SOURCE)

splits=["Train","Validation","Test"]


for split in splits:
    for cls in classes:
        os.makedirs(
            os.path.join(DEST,split,cls),
            exist_ok=True
        )


for cls in classes:

    images=os.listdir(
        os.path.join(SOURCE,cls)
    )


    train,val_test=train_test_split(
        images,
        test_size=0.30,
        random_state=42
    )


    val,test=train_test_split(
        val_test,
        test_size=0.50,
        random_state=42
    )


    data={
        "Train":train,
        "Validation":val,
        "Test":test
    }


    for split,files in data.items():

        for img in tqdm(files):

            src=os.path.join(
                SOURCE,
                cls,
                img
            )

            dst=os.path.join(
                DEST,
                split,
                cls,
                img
            )

            shutil.copy2(src,dst)


print("Dataset split completed ✅")

for split in ["Train","Validation","Test"]:

    print("\n",split)

    total=0

    for cls in os.listdir(os.path.join(DEST,split)):

        n=len(os.listdir(os.path.join(DEST,split,cls)))

        print(cls,":",n)

        total+=n

    print("Total:",total)

import os


SEVERITY_DATASET="/content/drive/MyDrive/AgriTrustNet++/Severity_Dataset"


severity_classes=[
    "Mild",
    "Moderate",
    "Severe",
    "Very_Severe"
]


for cls in severity_classes:

    os.makedirs(
        os.path.join(SEVERITY_DATASET,cls),
        exist_ok=True
    )


print("Severity folders created ✅")

!pip install opencv-python

import cv2
import numpy as np


def calculate_severity(image_path):

    image=cv2.imread(image_path)

    if image is None:
        return None,None


    image=cv2.cvtColor(
        image,
        cv2.COLOR_BGR2RGB
    )


    # Convert RGB to HSV

    hsv=cv2.cvtColor(
        image,
        cv2.COLOR_RGB2HSV
    )


    # Green leaf mask

    lower_green=np.array([25,30,20])
    upper_green=np.array([95,255,255])


    leaf_mask=cv2.inRange(
        hsv,
        lower_green,
        upper_green
    )


    leaf_pixels=np.sum(leaf_mask>0)


    if leaf_pixels==0:
        return None,None



    # Non-green region = disease region

    disease_mask=255-leaf_mask


    disease_pixels=np.sum(
        disease_mask>0
    )


    severity_percentage=(disease_pixels/leaf_pixels)*100



    if severity_percentage < 25:

        label="Mild"


    elif severity_percentage < 50:

        label="Moderate"


    elif severity_percentage < 75:

        label="Severe"


    else:

        label="Very_Severe"



    return severity_percentage,label

import os


sample=os.path.join(
    "/content/drive/MyDrive/AgriTrustNet++/Dataset_Split/Train/Brown_Spot",
    os.listdir(
        "/content/drive/MyDrive/AgriTrustNet++/Dataset_Split/Train/Brown_Spot"
    )[0]
)


score,label=calculate_severity(sample)


print("Severity percentage:",score)
print("Severity class:",label)

import os
import pandas as pd
from tqdm import tqdm


DATASET_PATH="/content/drive/MyDrive/AgriTrustNet++/Dataset_Split"


records=[]


for split in ["Train","Validation","Test"]:

    split_path=os.path.join(DATASET_PATH,split)


    for disease in os.listdir(split_path):

        disease_path=os.path.join(split_path,disease)


        for img in tqdm(os.listdir(disease_path)):

            img_path=os.path.join(
                disease_path,
                img
            )


            score,label = calculate_severity(img_path)


            if score is not None:

                records.append({

                    "split":split,

                    "image_path":img_path,

                    "disease_label":disease,

                    "severity_percentage":round(score,2),

                    "severity_class":label

                })


print("Total annotations:",len(records))


severity_df=pd.DataFrame(records)


severity_df.head()

CSV_PATH="/content/drive/MyDrive/AgriTrustNet++/severity_annotations.csv"

severity_df.to_csv(
    CSV_PATH,
    index=False
)


print("Severity CSV saved ✅")

print(
    severity_df["severity_class"].value_counts()
)

import pandas as pd


CSV_PATH="/content/drive/MyDrive/AgriTrustNet++/severity_annotations.csv"


df=pd.read_csv(CSV_PATH)


df.loc[
    df["disease_label"]=="Healthy",
    "severity_percentage"
]=0


df.loc[
    df["disease_label"]=="Healthy",
    "severity_class"
]="Healthy"


df.to_csv(
    CSV_PATH,
    index=False
)


print("Healthy severity corrected ✅")

print(df["severity_class"].value_counts())

import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import pandas as pd
import os

CSV_PATH="/content/drive/MyDrive/AgriTrustNet++/severity_annotations.csv"

df=pd.read_csv(CSV_PATH)

df.head()

disease_mapping = {
    "Healthy":0,
    "Bacterial_Blight":1,
    "Brown_Spot":2,
    "Leaf_Blast":3,
    "Tungro":4
}


severity_mapping = {
    "Healthy":0,
    "Mild":1,
    "Moderate":2,
    "Severe":3,
    "Very_Severe":4
}


df["disease_label"] = df["disease_label"].map(disease_mapping)

df["severity_label"] = df["severity_class"].map(severity_mapping)


df.head()

transform = transforms.Compose([

    transforms.Resize((224,224)),

    transforms.RandomHorizontalFlip(),

    transforms.RandomRotation(15),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

class AgriTrustDataset(Dataset):

    def __init__(self, dataframe, transform=None):

        self.df=dataframe
        self.transform=transform


    def __len__(self):

        return len(self.df)



    def __getitem__(self,index):

        row=self.df.iloc[index]


        image=Image.open(
            row["image_path"]
        ).convert("RGB")


        if self.transform:

            image=self.transform(image)


        disease=torch.tensor(
            row["disease_label"],
            dtype=torch.long
        )


        severity=torch.tensor(
            row["severity_label"],
            dtype=torch.long
        )


        return image,disease,severity

train_df=df[df["split"]=="Train"]

val_df=df[df["split"]=="Validation"]

test_df=df[df["split"]=="Test"]


print(len(train_df))
print(len(val_df))
print(len(test_df))

train_dataset=AgriTrustDataset(
    train_df,
    transform
)


val_dataset=AgriTrustDataset(
    val_df,
    transform
)


test_dataset=AgriTrustDataset(
    test_df,
    transform
)



train_loader=DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)


val_loader=DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False
)


test_loader=DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False
)

images,disease,severity=next(iter(train_loader))


print(images.shape)

print(disease.shape)

print(severity.shape)

import torch
import torch.nn as nn
import torchvision.models as models

class FeatureExtractor(nn.Module):

    def __init__(self):

        super().__init__()


        # EfficientNetV2-S

        efficient = models.efficientnet_v2_s(
            weights="DEFAULT"
        )

        self.efficientnet = nn.Sequential(
            *list(efficient.children())[:-1]
        )


        # ConvNeXt-Tiny

        convnext = models.convnext_tiny(
            weights="DEFAULT"
        )

        self.convnext = nn.Sequential(
            *list(convnext.children())[:-1]
        )



    def forward(self,x):

        f1=self.efficientnet(x)

        f2=self.convnext(x)


        f1=torch.flatten(
            f1,
            1
        )


        f2=torch.flatten(
            f2,
            1
        )


        return f1,f2



device="cuda" if torch.cuda.is_available() else "cpu"


extractor=FeatureExtractor().to(device)


dummy=torch.randn(
    2,
    3,
    224,
    224
).to(device)


f1,f2=extractor(dummy)


print(f1.shape)
print(f2.shape)

class FeatureFusion(nn.Module):

    def __init__(self):

        super().__init__()


        self.fusion = nn.Sequential(

            nn.Linear(1280 + 768, 1024),

            nn.BatchNorm1d(1024),

            nn.ReLU(),

            nn.Dropout(0.3)

        )


    def forward(self,f1,f2):

        combined=torch.cat(
            [f1,f2],
            dim=1
        )


        fused=self.fusion(combined)


        return fused

fusion=FeatureFusion().to(device)


fused_features=fusion(
    f1,
    f2
)


print(fused_features.shape)

class AttentionFusion(nn.Module):

    def __init__(self, feature_dim=1024):

        super().__init__()


        self.attention = nn.Sequential(

            nn.Linear(feature_dim, 256),

            nn.ReLU(),

            nn.Linear(256, feature_dim),

            nn.Sigmoid()

        )


    def forward(self,x):

        weights = self.attention(x)

        attended = x * weights

        return attended

attention = AttentionFusion().to(device)


attention_features = attention(
    fused_features
)


print(attention_features.shape)

class PredictionHeads(nn.Module):

    def __init__(self, feature_dim=1024):

        super().__init__()


        # Disease classification head
        self.disease_head = nn.Sequential(

            nn.Linear(feature_dim,512),

            nn.ReLU(),

            nn.Dropout(0.3),

            nn.Linear(512,5)

        )


        # Severity prediction head
        self.severity_head = nn.Sequential(

            nn.Linear(feature_dim,512),

            nn.ReLU(),

            nn.Dropout(0.3),

            nn.Linear(512,5)

        )


        # Confidence estimation head
        self.confidence_head = nn.Sequential(

            nn.Linear(feature_dim,256),

            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(256,1),

            nn.Sigmoid()

        )



    def forward(self,x):

        disease_output = self.disease_head(x)

        severity_output = self.severity_head(x)

        confidence_output = self.confidence_head(x)


        return (
            disease_output,
            severity_output,
            confidence_output
        )

heads = PredictionHeads().to(device)


disease_out, severity_out, confidence_out = heads(
    attention_features
)


print("Disease:", disease_out.shape)

print("Severity:", severity_out.shape)

print("Confidence:", confidence_out.shape)

class AgriTrustNetPP(nn.Module):

    def __init__(self):

        super().__init__()


        self.feature_extractor = FeatureExtractor()


        self.feature_fusion = FeatureFusion()


        self.attention = AttentionFusion()


        self.heads = PredictionHeads()



    def forward(self,x):


        # Feature extraction

        f1,f2 = self.feature_extractor(x)



        # Fusion

        fused = self.feature_fusion(
            f1,
            f2
        )



        # Attention refinement

        attended = self.attention(
            fused
        )



        # Multi task outputs

        disease, severity, confidence = self.heads(
            attended
        )


        return (
            disease,
            severity,
            confidence
        )

model = AgriTrustNetPP().to(device)


print("AgriTrustNet++ Model Created ✅")

images, disease_labels, severity_labels = next(iter(train_loader))


images = images.to(device)



disease_output, severity_output, confidence_output = model(images)



print("Disease output :", disease_output.shape)

print("Severity output:", severity_output.shape)

print("Confidence output:", confidence_output.shape)

import torch
import numpy as np
from sklearn.utils.class_weight import compute_class_weight


train_labels = train_df["disease_label"].values


class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(train_labels),
    y=train_labels
)


class_weights = torch.tensor(
    class_weights,
    dtype=torch.float32
).to(device)


print(class_weights)

disease_loss_fn = nn.CrossEntropyLoss(
    weight=class_weights
)


severity_loss_fn = nn.CrossEntropyLoss()


confidence_loss_fn = nn.MSELoss()

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-4,
    weight_decay=1e-5
)

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="min",
    patience=3,
    factor=0.5
)

import time


def train_one_epoch(model, loader):

    model.train()


    total_loss = 0

    disease_correct = 0
    severity_correct = 0

    total = 0


    for images, disease_labels, severity_labels in loader:


        images = images.to(device)

        disease_labels = disease_labels.to(device)

        severity_labels = severity_labels.to(device)



        optimizer.zero_grad()



        disease_out, severity_out, confidence_out = model(images)



        # Confidence target = correctness probability
        confidence_target = (
            disease_out.argmax(1) == disease_labels
        ).float().unsqueeze(1)



        loss1 = disease_loss_fn(
            disease_out,
            disease_labels
        )


        loss2 = severity_loss_fn(
            severity_out,
            severity_labels
        )


        loss3 = confidence_loss_fn(
            confidence_out,
            confidence_target
        )


        loss = (
            loss1
            +
            0.5*loss2
            +
            0.2*loss3
        )



        loss.backward()


        optimizer.step()



        total_loss += loss.item()



        disease_pred = disease_out.argmax(1)

        severity_pred = severity_out.argmax(1)



        disease_correct += (
            disease_pred == disease_labels
        ).sum().item()



        severity_correct += (
            severity_pred == severity_labels
        ).sum().item()



        total += images.size(0)



    avg_loss = total_loss / len(loader)


    disease_acc = 100*disease_correct/total

    severity_acc = 100*severity_correct/total



    return avg_loss, disease_acc, severity_acc

def validate(model, loader):

    model.eval()


    total_loss = 0

    disease_correct = 0

    severity_correct = 0

    total = 0



    with torch.no_grad():


        for images, disease_labels, severity_labels in loader:


            images=images.to(device)

            disease_labels=disease_labels.to(device)

            severity_labels=severity_labels.to(device)



            disease_out, severity_out, confidence_out = model(images)



            confidence_target = (
                disease_out.argmax(1)==disease_labels
            ).float().unsqueeze(1)



            loss1=disease_loss_fn(
                disease_out,
                disease_labels
            )


            loss2=severity_loss_fn(
                severity_out,
                severity_labels
            )


            loss3=confidence_loss_fn(
                confidence_out,
                confidence_target
            )


            loss=loss1+0.5*loss2+0.2*loss3



            total_loss+=loss.item()



            disease_correct += (
                disease_out.argmax(1)==disease_labels
            ).sum().item()


            severity_correct += (
                severity_out.argmax(1)==severity_labels
            ).sum().item()



            total += images.size(0)



    return (
        total_loss/len(loader),
        100*disease_correct/total,
        100*severity_correct/total
    )

!nvidia-smi

!nvidia-smi

import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

print(device)
print(torch.cuda.get_device_name(0))

from torch.utils.data import DataLoader

import os

print(os.path.exists("/content/drive/MyDrive/AgriTrustNet++/Dataset_Split"))
print(os.listdir("/content/drive/MyDrive/AgriTrustNet++"))

from google.colab import drive

drive.mount('/content/drive')

import os

print(os.listdir("/content/drive/MyDrive"))

import os

PROJECT_PATH="/content/drive/MyDrive/AgriTrustNet++"

print(os.listdir(PROJECT_PATH))

import pandas as pd

CSV_PATH = "/content/drive/MyDrive/AgriTrustNet++/severity_annotations.csv"

df = pd.read_csv(CSV_PATH)

print(df.head())
print(df["split"].value_counts())

from torchvision import transforms

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

from torch.utils.data import Dataset
from PIL import Image
import torch


class AgriTrustNetDataset(Dataset):

    def __init__(self, dataframe, transform=None):

        self.dataframe = dataframe.reset_index(drop=True)
        self.transform = transform


        self.disease_classes = {
            "Bacterial_Blight":0,
            "Brown_Spot":1,
            "Healthy":2,
            "Leaf_Blast":3,
            "Tungro":4
        }


        self.severity_classes = {
            "Mild":0,
            "Moderate":1,
            "Severe":2,
            "Very_Severe":3
        }



    def __len__(self):

        return len(self.dataframe)



    def __getitem__(self, index):

        row = self.dataframe.iloc[index]


        image_path = row["image_path"]


        image = Image.open(image_path).convert("RGB")


        if self.transform:
            image = self.transform(image)



        disease_label = torch.tensor(
            self.disease_classes[row["disease_label"]],
            dtype=torch.long
        )


        severity_label = torch.tensor(
            self.severity_classes[row["severity_class"]],
            dtype=torch.long
        )


        return image, disease_label, severity_label

train_df = df[df["split"]=="Train"]
val_df = df[df["split"]=="Validation"]
test_df = df[df["split"]=="Test"]


train_dataset = AgriTrustNetDataset(
    train_df,
    transform
)

val_dataset = AgriTrustNetDataset(
    val_df,
    transform
)

test_dataset = AgriTrustNetDataset(
    test_df,
    transform
)


print(len(train_dataset))
print(len(val_dataset))
print(len(test_dataset))

from torch.utils.data import DataLoader


train_loader = DataLoader(
    train_dataset,
    batch_size=8,
    shuffle=True,
    num_workers=2
)


val_loader = DataLoader(
    val_dataset,
    batch_size=8,
    shuffle=False,
    num_workers=2
)


test_loader = DataLoader(
    test_dataset,
    batch_size=8,
    shuffle=False,
    num_workers=2
)


print("DataLoaders created ✅")

import torch
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import pandas as pd
import os

from google.colab import drive

drive.mount('/content/drive')

from google.colab import drive

drive.mount('/content/drive')

PROJECT = "/content/drive/MyDrive/AgriTrustNet++"

print(os.listdir(PROJECT))

CSV_PATH = "/content/drive/MyDrive/AgriTrustNet++/severity_annotations.csv"

import pandas as pd

df = pd.read_csv(CSV_PATH)

print(df.head())
print(df["severity_class"].value_counts())

from google.colab import drive

drive.mount('/content/drive')

import os

BASE = "/content/drive/MyDrive"

print(os.listdir(BASE))

PROJECT = "/content/drive/MyDrive/AgriTrustNet++"

print(os.listdir(PROJECT))

import pandas as pd

CSV_PATH = "/content/drive/MyDrive/AgriTrustNet++/severity_annotations.csv"

df = pd.read_csv(CSV_PATH)

print(df.head())
print(df["severity_class"].value_counts())

import torch
from torch.utils.data import Dataset, DataLoader
from PIL import Image


class AgriTrustNetDataset(Dataset):

    def __init__(self, dataframe, transform=None):

        self.df = dataframe.reset_index(drop=True)
        self.transform = transform


        self.disease_classes = {
            "Healthy":0,
            "Brown_Spot":1,
            "Leaf_Blast":2,
            "Bacterial_Blight":3,
            "Tungro":4
        }


        self.severity_classes = {
            "Healthy":0,
            "Mild":1,
            "Moderate":2,
            "Severe":3,
            "Very_Severe":4
        }



    def __len__(self):
        return len(self.df)



    def __getitem__(self,index):

        row = self.df.iloc[index]


        image = Image.open(row["image_path"]).convert("RGB")


        if self.transform:
            image = self.transform(image)


        disease_label = torch.tensor(
            self.disease_classes[row["disease_label"]],
            dtype=torch.long
        )


        severity_label = torch.tensor(
            self.severity_classes[row["severity_class"]],
            dtype=torch.long
        )


        return image, disease_label, severity_label

train_df = df[df["split"]=="Train"]
val_df = df[df["split"]=="Validation"]
test_df = df[df["split"]=="Test"]


print(len(train_df))
print(len(val_df))
print(len(test_df))

from torchvision import transforms


transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])


print("Transform created ✅")

train_dataset = AgriTrustNetDataset(
    train_df,
    transform
)


val_dataset = AgriTrustNetDataset(
    val_df,
    transform
)


test_dataset = AgriTrustNetDataset(
    test_df,
    transform
)


print("Datasets created ✅")

image, disease, severity = train_dataset[0]

print(image.shape)
print(disease)
print(severity)

image, disease, severity = train_dataset[0]

print("Image shape:", image.shape)
print("Disease label:", disease)
print("Severity label:", severity)

from torch.utils.data import DataLoader


train_loader = DataLoader(
    train_dataset,
    batch_size=8,
    shuffle=True,
    num_workers=2
)


val_loader = DataLoader(
    val_dataset,
    batch_size=8,
    shuffle=False,
    num_workers=2
)


test_loader = DataLoader(
    test_dataset,
    batch_size=8,
    shuffle=False,
    num_workers=2
)


print("DataLoaders created ✅")

images, disease_labels, severity_labels = next(iter(train_loader))


print("Images:", images.shape)
print("Disease:", disease_labels.shape)
print("Severity:", severity_labels.shape)

import torch
import torch.nn as nn
import torchvision.models as models


device = "cuda" if torch.cuda.is_available() else "cpu"

print("Device:", device)

class FeatureExtractor(nn.Module):

    def __init__(self):

        super().__init__()


        efficient = models.efficientnet_v2_s(
            weights="DEFAULT"
        )

        self.efficientnet = nn.Sequential(
            *list(efficient.children())[:-1]
        )


        convnext = models.convnext_tiny(
            weights="DEFAULT"
        )

        self.convnext = nn.Sequential(
            *list(convnext.children())[:-1]
        )



    def forward(self,x):

        f1 = self.efficientnet(x)
        f2 = self.convnext(x)


        f1 = torch.flatten(f1,1)
        f2 = torch.flatten(f2,1)


        return f1,f2

extractor = FeatureExtractor().to(device)


dummy = torch.randn(
    2,3,224,224
).to(device)


f1,f2 = extractor(dummy)


print(f1.shape)
print(f2.shape)

import torch
import torch.nn as nn


class FeatureFusion(nn.Module):

    def __init__(self):
        super().__init__()

        self.fusion = nn.Sequential(

            nn.Linear(1280 + 768, 1024),

            nn.BatchNorm1d(1024),

            nn.ReLU(),

            nn.Dropout(0.3)
        )


    def forward(self, f1, f2):

        combined = torch.cat(
            [f1, f2],
            dim=1
        )

        fused = self.fusion(combined)

        return fused

fusion = FeatureFusion().to(device)


fused_features = fusion(
    f1,
    f2
)


print(fused_features.shape)

import torch
import torch.nn as nn


class AttentionModule(nn.Module):

    def __init__(self, dim):
        super().__init__()

        self.attention = nn.Sequential(
            nn.Linear(dim, dim),
            nn.Sigmoid()
        )


    def forward(self,x):

        weights = self.attention(x)

        return x * weights



class AgriHeads(nn.Module):

    def __init__(self):

        super().__init__()

        # Attention
        self.attention = AttentionModule(1024)


        # Disease classification
        self.disease_head = nn.Sequential(

            nn.Linear(1024,512),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(512,5)

        )


        # Severity classification
        self.severity_head = nn.Sequential(

            nn.Linear(1024,512),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(512,5)

        )


        # Confidence estimation
        self.confidence_head = nn.Sequential(

            nn.Linear(1024,256),
            nn.ReLU(),
            nn.Linear(256,1),
            nn.Sigmoid()

        )



    def forward(self,x):

        attended = self.attention(x)


        disease = self.disease_head(attended)

        severity = self.severity_head(attended)

        confidence = self.confidence_head(attended)


        return disease, severity, confidence

heads = AgriHeads().to(device)


disease_out, severity_out, confidence_out = heads(
    fused_features
)


print("Disease:", disease_out.shape)
print("Severity:", severity_out.shape)
print("Confidence:", confidence_out.shape)

import torch.nn as nn


class AgriTrustNetPP(nn.Module):

    def __init__(self):

        super().__init__()


        # Feature extraction
        self.feature_extractor = FeatureExtractor()


        # Fusion
        self.fusion = FeatureFusion()


        # Prediction heads with attention
        self.heads = AgriHeads()



    def forward(self,x):


        # Extract features

        f1, f2 = self.feature_extractor(x)



        # Fuse features

        fused = self.fusion(
            f1,
            f2
        )



        # Multi-task outputs

        disease, severity, confidence = self.heads(
            fused
        )


        return (
            disease,
            severity,
            confidence
        )

model = AgriTrustNetPP().to(device)


print("AgriTrustNet++ created successfully ✅")

images, disease_labels, severity_labels = next(iter(train_loader))


images = images.to(device)



disease_out, severity_out, confidence_out = model(images)



print("Disease output:", disease_out.shape)

print("Severity output:", severity_out.shape)

print("Confidence output:", confidence_out.shape)

import torch.nn as nn


disease_loss_fn = nn.CrossEntropyLoss()

severity_loss_fn = nn.CrossEntropyLoss()

confidence_loss_fn = nn.MSELoss()


print("Loss functions created ✅")

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-4,
    weight_decay=1e-5
)


print("Optimizer created ✅")

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="min",
    patience=3,
    factor=0.5
)


print("Scheduler created ✅")

images, disease_labels, severity_labels = next(iter(train_loader))


images = images.to(device)
disease_labels = disease_labels.to(device)
severity_labels = severity_labels.to(device)



disease_out, severity_out, confidence_out = model(images)



print(disease_out.shape)
print(severity_out.shape)
print(confidence_out.shape)

images, disease_labels, severity_labels = next(iter(train_loader))


images = images.to(device)
disease_labels = disease_labels.to(device)
severity_labels = severity_labels.to(device)



disease_out, severity_out, confidence_out = model(images)



print(disease_out.shape)
print(severity_out.shape)
print(confidence_out.shape)

def train_one_epoch(model, loader):

    model.train()

    running_loss = 0

    disease_correct = 0
    severity_correct = 0

    total = 0


    for images, disease_labels, severity_labels in loader:


        images = images.to(device)
        disease_labels = disease_labels.to(device)
        severity_labels = severity_labels.to(device)


        optimizer.zero_grad()


        # Forward pass
        disease_out, severity_out, confidence_out = model(images)



        # Confidence target
        confidence_target = (
            disease_out.argmax(1) == disease_labels
        ).float().unsqueeze(1)



        # Losses
        loss_disease = disease_loss_fn(
            disease_out,
            disease_labels
        )


        loss_severity = severity_loss_fn(
            severity_out,
            severity_labels
        )


        loss_confidence = confidence_loss_fn(
            confidence_out,
            confidence_target
        )


        total_loss = (
            loss_disease
            +
            0.5 * loss_severity
            +
            0.2 * loss_confidence
        )


        # Backpropagation

        total_loss.backward()

        optimizer.step()



        running_loss += total_loss.item()



        disease_pred = disease_out.argmax(1)

        severity_pred = severity_out.argmax(1)



        disease_correct += (
            disease_pred == disease_labels
        ).sum().item()


        severity_correct += (
            severity_pred == severity_labels
        ).sum().item()


        total += images.size(0)



    avg_loss = running_loss / len(loader)

    disease_acc = 100 * disease_correct / total

    severity_acc = 100 * severity_correct / total



    return avg_loss, disease_acc, severity_acc

def validate(model, loader):

    model.eval()


    running_loss = 0

    disease_correct = 0
    severity_correct = 0

    total = 0



    with torch.no_grad():

        for images, disease_labels, severity_labels in loader:


            images = images.to(device)
            disease_labels = disease_labels.to(device)
            severity_labels = severity_labels.to(device)



            disease_out, severity_out, confidence_out = model(images)



            confidence_target = (
                disease_out.argmax(1) == disease_labels
            ).float().unsqueeze(1)



            loss_disease = disease_loss_fn(
                disease_out,
                disease_labels
            )


            loss_severity = severity_loss_fn(
                severity_out,
                severity_labels
            )


            loss_confidence = confidence_loss_fn(
                confidence_out,
                confidence_target
            )


            total_loss = (
                loss_disease
                +
                0.5 * loss_severity
                +
                0.2 * loss_confidence
            )



            running_loss += total_loss.item()



            disease_correct += (
                disease_out.argmax(1)==disease_labels
            ).sum().item()



            severity_correct += (
                severity_out.argmax(1)==severity_labels
            ).sum().item()



            total += images.size(0)



    avg_loss = running_loss / len(loader)


    disease_acc = 100*disease_correct/total

    severity_acc = 100*severity_correct/total



    return avg_loss, disease_acc, severity_acc

import time
import torch


epochs = 2

best_accuracy = 0


train_losses = []
val_losses = []

train_disease_accs = []
val_disease_accs = []

train_severity_accs = []
val_severity_accs = []



for epoch in range(epochs):

    start_time = time.time()


    # Training

    train_loss, train_disease_acc, train_severity_acc = train_one_epoch(
        model,
        train_loader
    )


    # Validation

    val_loss, val_disease_acc, val_severity_acc = validate(
        model,
        val_loader
    )


    scheduler.step(val_loss)



    # Store history

    train_losses.append(train_loss)
    val_losses.append(val_loss)

    train_disease_accs.append(train_disease_acc)
    val_disease_accs.append(val_disease_acc)

    train_severity_accs.append(train_severity_acc)
    val_severity_accs.append(val_severity_acc)



    # Save best model

    if val_disease_acc > best_accuracy:

        best_accuracy = val_disease_acc

        torch.save(
            model.state_dict(),
            "/content/AgriTrustNetPP_best.pth"
        )

        print("Best model saved ✅")



    print(
        f"""
Epoch [{epoch+1}/{epochs}]
----------------------------

Train Loss        : {train_loss:.4f}

Train Disease Acc : {train_disease_acc:.2f}%

Val Loss          : {val_loss:.4f}

Val Disease Acc   : {val_disease_acc:.2f}%

Train Severity Acc: {train_severity_acc:.2f}%

Val Severity Acc  : {val_severity_acc:.2f}%


Time : {(time.time()-start_time):.2f} sec

"""
    )


print("========================")
print("Training Completed ✅")
print("Best Accuracy:",best_accuracy)
print("========================")

print(model)

for param in model.feature_extractor.parameters():
    param.requires_grad = False

print("Feature extractor frozen ✅")

optimizer = torch.optim.AdamW(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=1e-3,
    weight_decay=1e-5
)

print("Optimizer updated ✅")

# Freeze EfficientNet + ConvNeXt feature extractor

for param in model.feature_extractor.parameters():
    param.requires_grad = False

print("Backbone frozen ✅")

optimizer = torch.optim.AdamW(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=1e-3,
    weight_decay=1e-5
)

print("Optimizer updated ✅")

epochs = 5

print("Training epochs:", epochs)

optimizer = torch.optim.AdamW(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=1e-3,
    weight_decay=1e-5
)

print("Optimizer reset ✅")

epochs = 5

best_val_acc = 0


for epoch in range(epochs):

    print(f"\nEpoch {epoch+1}/{epochs}")


    # Training
    train_loss, train_disease_acc, train_severity_acc = train_one_epoch(
        model,
        train_loader
    )


    # Validation
    val_loss, val_disease_acc, val_severity_acc = validate(
        model,
        val_loader
    )


    if val_disease_acc > best_val_acc:

        best_val_acc = val_disease_acc

        torch.save(
            model.state_dict(),
            "/content/AgriTrustNetPP_best.pth"
        )

        print("Best model saved ✅")


    print("--------------------------------")
    print(f"Train Loss : {train_loss:.4f}")
    print(f"Train Disease Accuracy : {train_disease_acc:.2f}%")
    print(f"Val Loss : {val_loss:.4f}")
    print(f"Val Disease Accuracy : {val_disease_acc:.2f}%")
    print(f"Val Severity Accuracy : {val_severity_acc:.2f}%")

model.load_state_dict(
    torch.load("/content/AgriTrustNetPP_best.pth")
)

model.eval()

print("Best model loaded ✅")

from torch.utils.data import DataLoader

test_loader = DataLoader(
    test_dataset,
    batch_size=16,
    shuffle=False,
    num_workers=0
)

print("Test loader recreated ✅")

model.eval()

test_disease_correct = 0
test_severity_correct = 0
total = 0


with torch.no_grad():

    for images, disease_labels, severity_labels in test_loader:

        images = images.to(device)
        disease_labels = disease_labels.to(device)
        severity_labels = severity_labels.to(device)


        disease_output, severity_output, confidence_output = model(images)


        disease_pred = torch.argmax(disease_output, dim=1)
        severity_pred = torch.argmax(severity_output, dim=1)


        test_disease_correct += (disease_pred == disease_labels).sum().item()
        test_severity_correct += (severity_pred == severity_labels).sum().item()

        total += disease_labels.size(0)



disease_accuracy = 100 * test_disease_correct / total
severity_accuracy = 100 * test_severity_correct / total


print("Test Disease Accuracy:", round(disease_accuracy,2), "%")
print("Test Severity Accuracy:", round(severity_accuracy,2), "%")

from sklearn.metrics import classification_report
import numpy as np


all_disease_preds = []
all_disease_labels = []

all_severity_preds = []
all_severity_labels = []


model.eval()

with torch.no_grad():

    for images, disease_labels, severity_labels in test_loader:

        images = images.to(device)

        disease_labels = disease_labels.to(device)
        severity_labels = severity_labels.to(device)


        disease_output, severity_output, _ = model(images)


        disease_pred = torch.argmax(disease_output, dim=1)
        severity_pred = torch.argmax(severity_output, dim=1)


        all_disease_preds.extend(
            disease_pred.cpu().numpy()
        )

        all_disease_labels.extend(
            disease_labels.cpu().numpy()
        )


        all_severity_preds.extend(
            severity_pred.cpu().numpy()
        )

        all_severity_labels.extend(
            severity_labels.cpu().numpy()
        )



print("===== Disease Classification Report =====")

print(
    classification_report(
        all_disease_labels,
        all_disease_preds
    )
)


print("===== Severity Classification Report =====")

print(
    classification_report(
        all_severity_labels,
        all_severity_preds
    )
)

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns


cm = confusion_matrix(
    all_disease_labels,
    all_disease_preds
)


plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt="d"
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Disease Classification Confusion Matrix")

plt.show()

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns


cm = confusion_matrix(
    all_severity_labels,
    all_severity_preds
)


plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt="d"
)

plt.xlabel("Predicted Severity")
plt.ylabel("Actual Severity")
plt.title("Severity Classification Confusion Matrix")

plt.show()

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns


severity_cm = confusion_matrix(
    all_severity_labels,
    all_severity_preds
)


plt.figure(figsize=(8,6))

sns.heatmap(
    severity_cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)


plt.xlabel("Predicted Severity")
plt.ylabel("Actual Severity")
plt.title("Severity Classification Confusion Matrix")

plt.show()

!pip install grad-cam

import torch
import numpy as np
import matplotlib.pyplot as plt

from PIL import Image

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget

sample_path = test_df.iloc[10]["image_path"]

print(sample_path)

img = Image.open(sample_path).convert("RGB")

input_tensor = transform(img).unsqueeze(0).to(device)

print(input_tensor.shape)

print(model)

!pip install grad-cam

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

sample_path = test_df.iloc[10]["image_path"]

print(sample_path)

img = Image.open(sample_path).convert("RGB")

input_tensor = transform(img).unsqueeze(0).to(device)

print(input_tensor.shape)

target_layers = [
    model.feature_extractor.efficientnet[0][7]
]


cam = GradCAM(
    model=model,
    target_layers=target_layers
)

class DiseaseModelWrapper(torch.nn.Module):
    def __init__(self, model):
        super().__init__()
        self.model = model

    def forward(self, x):
        disease, severity, confidence = self.model(x)
        return disease


cam_model = DiseaseModelWrapper(model)
cam_model.to(device)
cam_model.eval()

target_layers = [
    model.feature_extractor.efficientnet[0][7]
]


cam = GradCAM(
    model=cam_model,
    target_layers=target_layers
)

for name, module in model.named_modules():
    if "conv" in name.lower():
        print(name)

cam = GradCAM(
    model=cam_model,
    target_layers=target_layers
)

target_layer = model.feature_extractor.convnext[0][7]

class DiseaseOnlyModel(torch.nn.Module):
    def __init__(self, model):
        super().__init__()
        self.model = model

    def forward(self, x):
        disease, severity, confidence = self.model(x)
        return disease


grad_model = DiseaseOnlyModel(model).to(device)

grad_model.eval()

from pytorch_grad_cam import GradCAM


cam = GradCAM(
    model=grad_model,
    target_layers=[
        target_layer
    ]
)

input_tensor.requires_grad = True

output = grad_model(input_tensor)

score = output[:, pred_class]

score.backward()

print("Gradient check completed ✅")

grayscale_cam = cam(
    input_tensor=input_tensor,
    targets=[
        ClassifierOutputTarget(pred_class)
    ]
)

grayscale_cam = grayscale_cam[0]


rgb_img = np.array(
    img.resize((224,224))
)/255.0


visualization = show_cam_on_image(
    rgb_img,
    grayscale_cam,
    use_rgb=True
)


plt.figure(figsize=(8,5))
plt.imshow(visualization)
plt.axis("off")
plt.title("AgriTrustNet++ Grad-CAM")
plt.show()

import torch
import matplotlib.pyplot as plt
import numpy as np


model.eval()

with torch.no_grad():

    disease_out, severity_out, confidence_out = model(input_tensor)

    disease_pred = torch.argmax(
        disease_out,
        dim=1
    ).item()

    severity_pred = torch.argmax(
        severity_out,
        dim=1
    ).item()

    confidence = torch.softmax(
        disease_out,
        dim=1
    )[0][disease_pred].item()



print("Disease class:", disease_pred)
print("Severity class:", severity_pred)
print("Confidence:", round(confidence*100,2), "%")

plt.figure(figsize=(12,5))


plt.subplot(1,2,1)

plt.imshow(img)

plt.axis("off")

plt.title("Original Leaf Image")



plt.subplot(1,2,2)

plt.imshow(visualization)

plt.axis("off")

plt.title(
    f"Grad-CAM\nConfidence: {confidence*100:.2f}%"
)


plt.show()

plt.figure(figsize=(5,5))

plt.imshow(visualization)

plt.axis("off")

plt.tight_layout()

plt.savefig(
    "/content/AgriTrustNet_GradCAM_Result.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import torch.nn as nn


def enable_dropout(model):
    for module in model.modules():
        if isinstance(module, nn.Dropout):
            module.train()


model.eval()
enable_dropout(model)

print("MC Dropout Enabled ✅")

import torch
import numpy as np


def mc_dropout_prediction(model, image, samples=20):

    predictions = []

    model.eval()
    enable_dropout(model)

    with torch.no_grad():

        for i in range(samples):

            disease_out, severity_out, confidence_out = model(image)

            prob = torch.softmax(
                disease_out,
                dim=1
            )

            predictions.append(
                prob.cpu().numpy()
            )


    predictions = np.array(predictions)

    return predictions

mc_results = mc_dropout_prediction(
    model,
    input_tensor,
    samples=20
)


mean_prediction = mc_results.mean(axis=0)

variance = mc_results.var(axis=0)


predicted_class = np.argmax(mean_prediction)


confidence = mean_prediction[0][predicted_class]


uncertainty = variance.mean()


print("Predicted Disease Class:", predicted_class)
print("Confidence:", confidence*100,"%")
print("Uncertainty:", uncertainty)

import torch
import torch.nn as nn


def enable_dropout(model):
    for module in model.modules():
        if isinstance(module, nn.Dropout):
            module.train()


model.eval()
enable_dropout(model)

print("Dropout enabled for MC sampling ✅")

import numpy as np


def mc_dropout_prediction(model, image, samples=20):

    predictions = []

    enable_dropout(model)

    with torch.no_grad():

        for i in range(samples):

            disease_output, severity_output, confidence_output = model(image)

            probability = torch.softmax(
                disease_output,
                dim=1
            )

            predictions.append(
                probability.cpu().numpy()
            )


    predictions = np.array(predictions)

    return predictions

mc_predictions = mc_dropout_prediction(
    model,
    input_tensor,
    samples=20
)


mean_prediction = mc_predictions.mean(axis=0)

uncertainty = mc_predictions.var(axis=0).mean()


predicted_class = np.argmax(
    mean_prediction
)


confidence = mean_prediction[0][predicted_class]


print("Predicted Disease Class:", predicted_class)
print("Confidence Score:", round(confidence*100,2), "%")
print("Uncertainty:", uncertainty)

import numpy as np
import torch


def mc_dropout_evaluate(model, loader, samples=20):

    all_confidences = []
    all_uncertainties = []

    model.eval()

    for images, disease_labels, severity_labels in loader:

        images = images.to(device)

        predictions = []

        enable_dropout(model)

        with torch.no_grad():

            for _ in range(samples):

                disease_out, severity_out, confidence_out = model(images)

                probs = torch.softmax(
                    disease_out,
                    dim=1
                )

                predictions.append(
                    probs.cpu().numpy()
                )


        predictions = np.array(predictions)


        mean_prob = predictions.mean(axis=0)

        variance = predictions.var(axis=0)


        confidence = np.max(
            mean_prob,
            axis=1
        )


        uncertainty = variance.mean(axis=0)


        all_confidences.extend(confidence)

        all_uncertainties.extend(uncertainty)



    return np.array(all_confidences), np.array(all_uncertainties)

confidence_scores, uncertainty_scores = mc_dropout_evaluate(
    model,
    test_loader,
    samples=20
)


print("Average Confidence:",
      round(confidence_scores.mean()*100,2),
      "%")


print("Average Uncertainty:",
      round(uncertainty_scores.mean(),5))

import matplotlib.pyplot as plt


plt.figure(figsize=(7,5))

plt.hist(
    confidence_scores*100,
    bins=20
)

plt.xlabel("Confidence Score (%)")
plt.ylabel("Number of Samples")

plt.title(
    "Prediction Confidence Distribution of AgriTrustNet++"
)

plt.show()

import pandas as pd

results = {
    "Metric": [
        "Disease Classification Accuracy",
        "Severity Classification Accuracy",
        "Disease Precision",
        "Disease Recall",
        "Disease F1-score",
        "Severity Macro F1-score",
        "Average Confidence",
        "Average Uncertainty"
    ],

    "Value": [
        "100%",
        "96.32%",
        "1.00",
        "1.00",
        "1.00",
        "0.95",
        "99.97%",
        "0.00001"
    ]
}


result_df = pd.DataFrame(results)

result_df

result_df.to_csv(
    "/content/AgriTrustNet_Final_Results.csv",
    index=False
)

print("Final results saved ✅")

def generate_recommendation(severity_class, disease_label):

    recommendations = {

        "Healthy": {
            "action": "No disease detected",
            "advice": "Continue regular monitoring and maintain proper irrigation."
        },

        "Mild": {
            "action": "Early-stage infection control",
            "advice": "Remove affected leaves, improve field sanitation, and monitor regularly."
        },

        "Moderate": {
            "action": "Apply disease management practices",
            "advice": "Use recommended fungicide/bio-control methods and maintain proper nutrient balance."
        },

        "Severe": {
            "action": "Immediate intervention required",
            "advice": "Apply suitable crop protection measures and consult agricultural experts."
        },

        "Very_Severe": {
            "action": "Critical disease condition",
            "advice": "Immediate expert consultation required to prevent crop loss."
        }
    }


    return recommendations[severity_class]

result = generate_recommendation(
    "Severe",
    "Brown Spot"
)


print(result)

disease_classes = [
    "Bacterial Blight",
    "Brown Spot",
    "Healthy",
    "Leaf Blast",
    "Tungro"
]


severity_classes = [
    "Healthy",
    "Mild",
    "Moderate",
    "Severe",
    "Very Severe"
]

def get_recommendation(disease, severity):

    recommendations = {


        "Healthy":
        "No treatment required. Maintain regular crop monitoring.",



        "Mild":
        "Early infection detected. Remove affected leaves and monitor crop regularly.",



        "Moderate":
        "Disease progression detected. Apply suitable crop protection practices.",



        "Severe":
        "Immediate disease management required. Apply recommended control measures.",



        "Very Severe":
        "Critical condition. Consult agricultural experts immediately."
    }


    return recommendations[severity]

def calculate_severity_score(severity):

    score_mapping = {

        "Healthy":0,

        "Mild":20,

        "Moderate":45,

        "Severe":70,

        "Very Severe":90

    }


    return score_mapping[severity]

import torch
import torch.nn as nn
import numpy as np



def enable_dropout(model):

    for module in model.modules():

        if isinstance(module, nn.Dropout):

            module.train()



def predict_uncertainty(model, image, samples=20):


    predictions=[]


    model.eval()

    enable_dropout(model)


    with torch.no_grad():

        for _ in range(samples):

            disease_out, severity_out, confidence_out = model(image)


            prob = torch.softmax(
                disease_out,
                dim=1
            )


            predictions.append(
                prob.cpu().numpy()
            )


    predictions=np.array(predictions)


    mean_prediction = predictions.mean(axis=0)


    uncertainty = predictions.var().mean()


    confidence = np.max(mean_prediction)


    return confidence, uncertainty

def predict_agritrustnet(image_path):


    from PIL import Image


    img = Image.open(image_path).convert("RGB")


    input_tensor = transform(img).unsqueeze(0).to(device)



    model.eval()



    with torch.no_grad():


        disease_out, severity_out, confidence_out = model(
            input_tensor
        )


        disease_pred = torch.argmax(
            disease_out,
            dim=1
        ).item()



        severity_pred = torch.argmax(
            severity_out,
            dim=1
        ).item()



    disease = disease_classes[disease_pred]


    severity = severity_classes[severity_pred]



    confidence, uncertainty = predict_uncertainty(
        model,
        input_tensor
    )



    severity_score = calculate_severity_score(
        severity
    )



    recommendation = get_recommendation(
        disease,
        severity
    )



    print("="*40)

    print(" AgriTrustNet++ Prediction Report ")

    print("="*40)



    print(
        "Disease:",
        disease
    )


    print(
        "Severity:",
        severity
    )


    print(
        "Severity Score:",
        severity_score,
        "%"
    )


    print(
        "Confidence:",
        round(confidence*100,2),
        "%"
    )


    print(
        "Uncertainty:",
        round(uncertainty,6)
    )


    print(
        "Recommendation:"
    )


    print(
        recommendation
    )


    print("="*40)



    return {

        "Disease":disease,

        "Severity":severity,

        "Severity Score":severity_score,

        "Confidence":confidence,

        "Uncertainty":uncertainty,

        "Recommendation":recommendation

    }

sample_image = test_df.iloc[10]["image_path"]


result = predict_agritrustnet(
    sample_image
)

def predict_uncertainty(model, image, samples=20):

    predictions=[]

    model.eval()
    enable_dropout(model)

    with torch.no_grad():

        for _ in range(samples):

            disease_out, severity_out, confidence_out = model(image)

            prob = torch.softmax(
                disease_out,
                dim=1
            )

            predictions.append(
                prob.cpu().numpy()
            )


    predictions = np.array(predictions)

    mean_prediction = predictions.mean(axis=0)


    # entropy based uncertainty
    entropy = -np.sum(
        mean_prediction * np.log(mean_prediction + 1e-8)
    )


    confidence = np.max(mean_prediction)


    return confidence, entropy

result = predict_agritrustnet(sample_image)

severity = severity_classes[severity_pred]

# Severity consistency correction

if disease != "Healthy" and severity == "Healthy":

    severity = "Mild"

for i in range(5):

    sample_image = test_df.iloc[i]["image_path"]

    print("\nImage:", i)

    result = predict_agritrustnet(sample_image)

print(train_df["disease_label"].unique())

print(train_df["severity_class"].unique())

print(train_dataset.disease_classes)

print(train_dataset.severity_classes)

disease_classes = [
    "Healthy",
    "Brown Spot",
    "Leaf Blast",
    "Bacterial Blight",
    "Tungro"
]


severity_classes = [
    "Healthy",
    "Mild",
    "Moderate",
    "Severe",
    "Very Severe"
]

def get_recommendation(disease, severity):

    if disease == "Healthy":
        return "No treatment required. Maintain regular crop monitoring."

    if severity == "Mild":
        return "Early infection detected. Monitor affected leaves and improve crop management."

    if severity == "Moderate":
        return "Apply suitable disease management practices."

    if severity == "Severe":
        return "Immediate disease control measures are recommended."

    if severity == "Very Severe":
        return "Critical condition. Consult agricultural experts immediately."

for i in range(5):

    sample_image = test_df.iloc[i]["image_path"]

    print("\nImage:", i)

    result = predict_agritrustnet(sample_image)

for i in range(5):
    print(test_df.iloc[i]["image_path"])

for i in range(5):
    print(
        "Image:",
        i,
        "Actual:",
        test_df.iloc[i]["disease_label"],
        "Severity:",
        test_df.iloc[i]["severity_class"]
    )

sample_image = test_df.iloc[10]["image_path"]

img = Image.open(sample_image).convert("RGB")

input_tensor = transform(img).unsqueeze(0).to(device)


model.eval()

with torch.no_grad():

    disease_out, severity_out, confidence_out = model(input_tensor)


print("Disease probabilities:")
print(torch.softmax(disease_out, dim=1))


print("\nSeverity probabilities:")
print(torch.softmax(severity_out, dim=1))

print(best_val_acc)

print(model)

sample_image = test_df.iloc[10]["image_path"]

img = Image.open(sample_image).convert("RGB")

input_tensor = transform(img).unsqueeze(0).to(device)


model.eval()

with torch.no_grad():

    disease_out, severity_out, confidence_out = model(input_tensor)


disease_prob = torch.softmax(disease_out, dim=1)

severity_prob = torch.softmax(severity_out, dim=1)


print("Disease probability:")
print(disease_prob)


print("\nPredicted disease index:")
print(torch.argmax(disease_prob, dim=1).item())


print("\nSeverity probability:")
print(severity_prob)


print("\nPredicted severity index:")
print(torch.argmax(severity_prob, dim=1).item())

print("Actual Disease:",
      test_df.iloc[10]["disease_label"])

print("Actual Severity:",
      test_df.iloc[10]["severity_class"])

import random

for i in range(5):

    idx = random.randint(0, len(test_df)-1)

    sample_image = test_df.iloc[idx]["image_path"]

    print("\nImage index:", idx)

    print("Actual:",
          test_df.iloc[idx]["disease_label"])

    result = predict_agritrustnet(sample_image)

for name, module in model.named_modules():
    if isinstance(module, torch.nn.Dropout):
        print(name, module.training)

import pandas as pd

demo_results = []

for i in range(10):

    idx = random.randint(0, len(test_df)-1)

    sample_image = test_df.iloc[idx]["image_path"]

    output = predict_agritrustnet(sample_image)

    output["Actual Disease"] = test_df.iloc[idx]["disease_label"]

    demo_results.append(output)


demo_df = pd.DataFrame(demo_results)

demo_df

demo_df.to_csv(
    "/content/AgriTrustNetPP_Demo_Results.csv",
    index=False
)

print("Demo results saved ✅")

import matplotlib.pyplot as plt
import numpy as np


# Confidence scores collected from test predictions
# Replace with your actual confidence_scores list if available

confidence_scores = np.array(confidence_scores) * 100


plt.figure(figsize=(7,4))

plt.hist(
    confidence_scores,
    bins=20
)

plt.xlabel("Confidence Score (%)")
plt.ylabel("Number of Samples")

plt.title(
    "Confidence Score Distribution of AgriTrustNet++"
)

plt.xlim(90,100)

plt.grid(
    alpha=0.3
)

plt.tight_layout()


# Save for IEEE paper
plt.savefig(
    "AgriTrustNetPP_Confidence_Distribution.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import matplotlib.pyplot as plt


# Replace these values with your actual epoch values
train_acc = [97.29, 99.08, 98.96, 98.79, 99.00]
val_acc   = [99.03, 100.00, 100.00, 100.00, 100.00]

train_loss = [0.2913, 0.1583, 0.1670, 0.1634, 0.1500]
val_loss   = [0.1463, 0.1081, 0.0762, 0.0751, 0.0700]


epochs = range(1, len(train_acc)+1)


# Accuracy Graph
plt.figure(figsize=(7,4))

plt.plot(
    epochs,
    train_acc,
    marker='o',
    label="Training Accuracy"
)

plt.plot(
    epochs,
    val_acc,
    marker='s',
    label="Validation Accuracy"
)


plt.xlabel("Epochs")
plt.ylabel("Accuracy (%)")

plt.title(
    "Training and Validation Accuracy of AgriTrustNet++"
)

plt.legend()
plt.grid(alpha=0.3)

plt.ylim(90,101)

plt.tight_layout()

plt.savefig(
    "AgriTrustNetPP_Accuracy_Curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

plt.figure(figsize=(7,4))

plt.plot(
    epochs,
    train_loss,
    marker='o',
    label="Training Loss"
)

plt.plot(
    epochs,
    val_loss,
    marker='s',
    label="Validation Loss"
)


plt.xlabel("Epochs")
plt.ylabel("Loss")

plt.title(
    "Training and Validation Loss of AgriTrustNet++"
)

plt.legend()
plt.grid(alpha=0.3)

plt.tight_layout()


plt.savefig(
    "AgriTrustNetPP_Loss_Curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()